# Configuration file for the Cell Tracking Pipeline
# -----------------------------------------------
# This file contains all configurable parameters for the cell tracking pipeline

# Input/Output settings
image_path: "data/sample_image.tif"  # Default input image path
output_dir: "data/output"            # Default output directory

# Preprocessing parameters
preprocessing:
  inpaint: true                    # Remove imaging artifacts
  gaussian_blur_enabled: false     # Optional noise reduction
  gaussian_blur_sigma: 1.0         # Blur intensity if enabled
  gamma_correction_enabled: false  # Optional contrast adjustment
  gamma: 1.2                      # Gamma correction value if enabled

# Segmentation parameters
segmentation:
  bbox_threshold: 0.4             # Confidence threshold for cell detection
  quadrant_mode: false           # Whether to use quadrant processing
  device: "auto"                 # Auto-select processing device (CPU/GPU)

# Post-processing parameters
postprocessing:
  min_object_size: 200           # Minimum cell size in pixels
  merge_overlap_threshold: 0.5   # Threshold for merging overlapping cells
  remove_small_objects: true     # Filter out small objects
  min_size: 20                   # Minimum size threshold for filtering 