# Conda environment configuration for Cell Tracker
# ---------------------------------------------
# This file defines all dependencies required to run the cell tracking pipeline

name: cell_tracker
channels:
  - conda-forge    # Primary channel for most dependencies
  - pytorch        # Required for PyTorch installation
  - defaults      # Fallback channel
dependencies:
  - python=3.9    # Base Python version
  - numpy>=1.21.0  # Array operations
  - opencv>=4.5.0  # Image processing
  - pytorch>=1.9.0 # Deep learning framework
  - scikit-image>=0.19.0  # Image processing utilities
  - pyyaml>=5.4.0  # Configuration file handling
  - tqdm>=4.65.0   # Progress bars
  - pip
  - pip:
    - cellSAM @ git+https://github.com/vanvalenlab/cellSAM.git  # Cell segmentation model