name: cell_tracker
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.21.0
  - opencv>=4.5.0
  - pytorch>=1.9.0
  - scikit-image>=0.19.0
  - pyyaml>=5.4.0
  - tqdm>=4.65.0
  - pip
  - pip:
  - cellSAM @ git+https://github.com/vanvalenlab/cellSAM.git 